
-- EXPANDED SEED DATA
-- generated by scripts/generate_seed_data.js

-- Clear existing generated data to prevent duplicate ID errors
DELETE FROM public.vehicles WHERE id > 6;


insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  7, 'Rolls-Royce Silver Shadow', 1978, 50452, '17,547', 'Petrol', 'Targa', 'Manual', 'Cream White', 
  'https://images.unsplash.com/photo-8WlP4rZg8IY?auto=format&fit=crop&w=800&q=80', 'Investment Grade',
  'VIN698831', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1978 Rolls-Royce Silver Shadow. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  8, 'Rolls-Royce Wraith', 1958, 120310, '60,541', 'Petrol', 'Roadster', 'Manual', 'Cream White', 
  'https://images.unsplash.com/photo-0dY-8yTJfey?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN280750', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1958 Rolls-Royce Wraith. Finished in stunning Cream White, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  9, 'Rolls-Royce Corniche', 1988, 144412, '26,790', 'Petrol', 'Coupe', 'Manual', 'ChampagneGold', 
  'https://images.unsplash.com/photo-nDV6ahWLvEg?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN216370', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1988 Rolls-Royce Corniche. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  10, 'Rolls-Royce Silver Cloud', 1955, 143784, '87,301', 'Petrol', 'Convertible', 'Manual', 'Midnight Blue', 
  'https://images.unsplash.com/photo-Cjfl8r_eYXg?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN492870', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1955 Rolls-Royce Silver Cloud in Midnight Blue represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  11, 'Rolls-Royce Wraith', 1958, 160013, '91,932', 'Petrol', 'Roadster', 'Manual', 'Cream White', 
  'https://images.unsplash.com/photo-X16zXcbxU4U?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN768997', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1958 Rolls-Royce Wraith. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  12, 'Rolls-Royce Silver Cloud', 1958, 115663, '93,175', 'Petrol', 'Sedan', 'Automatic', 'ChampagneGold', 
  'https://images.unsplash.com/photo-9GzW50h21jE?auto=format&fit=crop&w=800&q=80', 'Rare Find',
  'VIN544605', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1958 Rolls-Royce Silver Cloud in ChampagneGold represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  13, 'Rolls-Royce Corniche', 1981, 155573, '61,297', 'Petrol', 'Convertible', 'Automatic', 'British Racing Green', 
  'https://images.unsplash.com/photo-8WlP4rZg8IY?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN495746', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1981 Rolls-Royce Corniche with only 61,297 miles, presented in immaculate British Racing Green.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  14, 'Rolls-Royce Silver Cloud', 1959, 184786, '78,006', 'Petrol', 'Convertible', '5-Speed Manual', 'ChampagneGold', 
  'https://images.unsplash.com/photo-0dY-8yTJfey?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN544422', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1959 Rolls-Royce Silver Cloud with only 78,006 miles, presented in immaculate ChampagneGold.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  15, 'Rolls-Royce Wraith', 1948, 177719, '24,538', 'Petrol', 'Coupe', 'Manual', 'ChampagneGold', 
  'https://images.unsplash.com/photo-nDV6ahWLvEg?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN324371', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1948 Rolls-Royce Wraith. Finished in stunning ChampagneGold, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  16, 'Rolls-Royce Silver Cloud', 1964, 126016, '79,137', 'Petrol', 'Roadster', 'Automatic', 'Black', 
  'https://images.unsplash.com/photo-Cjfl8r_eYXg?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN981768', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1964 Rolls-Royce Silver Cloud with only 79,137 miles, presented in immaculate Black.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  17, 'Rolls-Royce Phantom V', 1966, 319611, '55,356', 'Petrol', 'Coupe', 'Manual', 'Cream White', 
  'https://images.unsplash.com/photo-X16zXcbxU4U?auto=format&fit=crop&w=800&q=80', 'Concours Winner',
  'VIN802089', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1966 Rolls-Royce Phantom V in Cream White represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  18, 'Rolls-Royce Silver Shadow', 1971, 109404, '56,489', 'Petrol', 'Coupe', 'Manual', 'British Racing Green', 
  'https://images.unsplash.com/photo-9GzW50h21jE?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN256266', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1971 Rolls-Royce Silver Shadow with only 56,489 miles, presented in immaculate British Racing Green.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  19, 'Rolls-Royce Corniche', 1988, 148771, '10,493', 'Petrol', 'Sedan', '5-Speed Manual', 'Midnight Blue', 
  'https://images.unsplash.com/photo-8WlP4rZg8IY?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN977855', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1988 Rolls-Royce Corniche in Midnight Blue represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  20, 'Rolls-Royce Silver Shadow', 1977, 62681, '92,106', 'Petrol', 'Targa', 'Automatic', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-0dY-8yTJfey?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN527553', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1977 Rolls-Royce Silver Shadow in Rosso Corsa represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  21, 'Rolls-Royce Wraith', 1949, 136575, '87,738', 'Petrol', 'Targa', '5-Speed Manual', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-nDV6ahWLvEg?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN159308', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1949 Rolls-Royce Wraith in Rosso Corsa represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  22, 'Jaguar XK120', 1951, 155323, '74,680', 'Petrol', 'Convertible', '4-Speed Manual', 'ChampagneGold', 
  'https://images.unsplash.com/photo-m3m-lnR90uM?auto=format&fit=crop&w=800&q=80', 'Investment Grade',
  'VIN403724', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1951 Jaguar XK120 with only 74,680 miles, presented in immaculate ChampagneGold.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  23, 'Jaguar XK150', 1959, 135250, '20,865', 'Petrol', 'Coupe', 'Manual', 'ChampagneGold', 
  'https://images.unsplash.com/photo-N9Pf2J656aQ?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN823373', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1959 Jaguar XK150. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  24, 'Jaguar E-Type Roadster', 1964, 240475, '82,421', 'Petrol', 'Coupe', 'Automatic', 'British Racing Green', 
  'https://images.unsplash.com/photo-Iu6parQAO-U?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN527131', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1964 Jaguar E-Type Roadster. Finished in stunning British Racing Green, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  25, 'Jaguar XK150', 1957, 122530, '3,001', 'Petrol', 'Roadster', '5-Speed Manual', 'Black', 
  'https://images.unsplash.com/photo-jR4Zf-riEjI?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN118621', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1957 Jaguar XK150. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  26, 'Jaguar XK150', 1957, 144219, '72,027', 'Petrol', 'Convertible', '5-Speed Manual', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-OS2w2lMvA7g?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN701296', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1957 Jaguar XK150. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  27, 'Jaguar E-Type Roadster', 1963, 174145, '42,202', 'Petrol', 'Targa', 'Automatic', 'British Racing Green', 
  'https://images.unsplash.com/photo-F_r83JpD0yU?auto=format&fit=crop&w=800&q=80', 'Concours Winner',
  'VIN852290', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1963 Jaguar E-Type Roadster in British Racing Green represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  28, 'Jaguar Mark II', 1962, 42951, '62,733', 'Petrol', 'Convertible', 'Manual', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-m3m-lnR90uM?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN461917', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1962 Jaguar Mark II. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  29, 'Jaguar XK120', 1953, 178471, '69,560', 'Petrol', 'Targa', 'Automatic', 'Black', 
  'https://images.unsplash.com/photo-N9Pf2J656aQ?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN484155', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1953 Jaguar XK120 with only 69,560 miles, presented in immaculate Black.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  30, 'Jaguar Mark II', 1962, 67415, '20,335', 'Petrol', 'Coupe', '4-Speed Manual', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-Iu6parQAO-U?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN554873', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1962 Jaguar Mark II with only 20,335 miles, presented in immaculate Rosso Corsa.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  31, 'Jaguar Mark II', 1959, 57976, '87,233', 'Petrol', 'Roadster', '5-Speed Manual', 'Cream White', 
  'https://images.unsplash.com/photo-jR4Zf-riEjI?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN691346', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1959 Jaguar Mark II in Cream White represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  32, 'Jaguar E-Type Roadster', 1964, 239913, '39,482', 'Petrol', 'Targa', 'Automatic', 'British Racing Green', 
  'https://images.unsplash.com/photo-OS2w2lMvA7g?auto=format&fit=crop&w=800&q=80', 'Concours Winner',
  'VIN733869', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1964 Jaguar E-Type Roadster. Finished in stunning British Racing Green, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  33, 'Jaguar XK150', 1959, 139586, '36,742', 'Petrol', 'Sedan', 'Automatic', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-F_r83JpD0yU?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN609053', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1959 Jaguar XK150 in Rosso Corsa represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  34, 'Jaguar E-Type Roadster', 1970, 169404, '72,140', 'Petrol', 'Sedan', 'Manual', 'ChampagneGold', 
  'https://images.unsplash.com/photo-m3m-lnR90uM?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN145016', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1970 Jaguar E-Type Roadster in ChampagneGold represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  35, 'Jaguar XK150', 1960, 147457, '45,341', 'Petrol', 'Convertible', 'Manual', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-N9Pf2J656aQ?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN523902', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1960 Jaguar XK150. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  36, 'Jaguar Mark II', 1960, 35909, '94,982', 'Petrol', 'Coupe', 'Manual', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-Iu6parQAO-U?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN121658', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1960 Jaguar Mark II in Rosso Corsa represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  37, 'Mercedes-Benz 190SL', 1960, 141332, '83,999', 'Petrol', 'Sedan', '5-Speed Manual', 'Silver', 
  'https://images.unsplash.com/photo-FD6Rdf1Qyv0?auto=format&fit=crop&w=800&q=80', 'Concours Winner',
  'VIN926443', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1960 Mercedes-Benz 190SL. Finished in stunning Silver, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  38, 'Mercedes-Benz 280 SL Pagoda', 1964, 157739, '11,170', 'Petrol', 'Sedan', 'Automatic', 'ChampagneGold', 
  'https://images.unsplash.com/photo-Y3nekhZ-c7E?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN579149', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1964 Mercedes-Benz 280 SL Pagoda. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  39, 'Mercedes-Benz 300SL Gullwing', 1959, 1447979, '50,805', 'Petrol', 'Roadster', '5-Speed Manual', 'ChampagneGold', 
  'https://images.unsplash.com/photo-3Z70SD8L530?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN966401', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1959 Mercedes-Benz 300SL Gullwing. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  40, 'Mercedes-Benz 280 SL Pagoda', 1971, 157084, '4,707', 'Petrol', 'Convertible', 'Automatic', 'Black', 
  'https://images.unsplash.com/photo-k1tOcafJg48?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN208418', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1971 Mercedes-Benz 280 SL Pagoda in Black represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  41, 'Mercedes-Benz 280 SL Pagoda', 1967, 138415, '68,197', 'Petrol', 'Coupe', '4-Speed Manual', 'Black', 
  'https://images.unsplash.com/photo-6lQFN3jQPHE?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN467622', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1967 Mercedes-Benz 280 SL Pagoda in Black represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  42, 'Mercedes-Benz 190SL', 1963, 112961, '17,231', 'Petrol', 'Targa', 'Manual', 'ChampagneGold', 
  'https://images.unsplash.com/photo-N9Pf2J656aQ?auto=format&fit=crop&w=800&q=80', 'Concours Winner',
  'VIN191321', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1963 Mercedes-Benz 190SL in ChampagneGold represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  43, 'Mercedes-Benz 600 Pullman', 1967, 488546, '70,550', 'Petrol', 'Roadster', 'Manual', 'Black', 
  'https://images.unsplash.com/photo-FD6Rdf1Qyv0?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN283453', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1967 Mercedes-Benz 600 Pullman. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  44, 'Mercedes-Benz 190SL', 1958, 146617, '16,060', 'Petrol', 'Targa', 'Automatic', 'Cream White', 
  'https://images.unsplash.com/photo-Y3nekhZ-c7E?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN769265', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1958 Mercedes-Benz 190SL. Finished in stunning Cream White, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  45, 'Mercedes-Benz 300SL Gullwing', 1954, 1422374, '76,735', 'Petrol', 'Roadster', '5-Speed Manual', 'Midnight Blue', 
  'https://images.unsplash.com/photo-3Z70SD8L530?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN285861', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1954 Mercedes-Benz 300SL Gullwing in Midnight Blue represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  46, 'Mercedes-Benz 280 SL Pagoda', 1969, 111637, '3,852', 'Petrol', 'Roadster', '4-Speed Manual', 'British Racing Green', 
  'https://images.unsplash.com/photo-k1tOcafJg48?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN881528', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1969 Mercedes-Benz 280 SL Pagoda with only 3,852 miles, presented in immaculate British Racing Green.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  47, 'Mercedes-Benz 300SL Gullwing', 1961, 1459565, '27,477', 'Petrol', 'Convertible', '4-Speed Manual', 'Black', 
  'https://images.unsplash.com/photo-6lQFN3jQPHE?auto=format&fit=crop&w=800&q=80', 'Investment Grade',
  'VIN490567', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1961 Mercedes-Benz 300SL Gullwing with only 27,477 miles, presented in immaculate Black.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  48, 'Mercedes-Benz 190SL', 1961, 175836, '46,688', 'Petrol', 'Targa', '5-Speed Manual', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-N9Pf2J656aQ?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN587566', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1961 Mercedes-Benz 190SL. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  49, 'Mercedes-Benz 600 Pullman', 1972, 564892, '89,179', 'Petrol', 'Convertible', '4-Speed Manual', 'Black', 
  'https://images.unsplash.com/photo-FD6Rdf1Qyv0?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN869394', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1972 Mercedes-Benz 600 Pullman. Finished in stunning Black, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  50, 'Mercedes-Benz 280 SL Pagoda', 1969, 80811, '76,373', 'Petrol', 'Sedan', 'Manual', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-Y3nekhZ-c7E?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN738561', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1969 Mercedes-Benz 280 SL Pagoda. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  51, 'Mercedes-Benz 600 Pullman', 1969, 563731, '63,234', 'Petrol', 'Convertible', '4-Speed Manual', 'ChampagneGold', 
  'https://images.unsplash.com/photo-3Z70SD8L530?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN575182', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1969 Mercedes-Benz 600 Pullman with only 63,234 miles, presented in immaculate ChampagneGold.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  52, 'Aston Martin DB4 GT', 1960, 1506294, '40,086', 'Petrol', 'Sedan', '5-Speed Manual', 'Black', 
  'https://images.unsplash.com/photo-84bbe3c3fd98?auto=format&fit=crop&w=800&q=80', 'Rare Find',
  'VIN377778', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1960 Aston Martin DB4 GT in Black represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  53, 'Aston Martin DB6', 1966, 409080, '29,111', 'Petrol', 'Sedan', 'Automatic', 'Gunmetal Grey', 
  'https://images.unsplash.com/photo-LpbyDENbQQg?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN320089', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1966 Aston Martin DB6. Finished in stunning Gunmetal Grey, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  54, 'Aston Martin DB5', 1964, 1048172, '11,263', 'Petrol', 'Roadster', '4-Speed Manual', 'ChampagneGold', 
  'https://images.unsplash.com/photo-hE49D3lQZ5w?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN277419', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1964 Aston Martin DB5. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  55, 'Aston Martin DB5', 1964, 1048348, '4,463', 'Petrol', 'Sedan', 'Manual', 'Silver', 
  'https://images.unsplash.com/photo-e_D3Z3K0i5g?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN684270', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1964 Aston Martin DB5. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  56, 'Aston Martin DB6', 1966, 494309, '82,985', 'Petrol', 'Sedan', 'Manual', 'ChampagneGold', 
  'https://images.unsplash.com/photo-aq5X00a5G6A?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN142107', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1966 Aston Martin DB6. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  57, 'Aston Martin DB4 GT', 1962, 2152220, '75,822', 'Petrol', 'Targa', '4-Speed Manual', 'Gunmetal Grey', 
  'https://images.unsplash.com/photo-vpOeCk5amPU?auto=format&fit=crop&w=800&q=80', 'Rare Find',
  'VIN449939', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1962 Aston Martin DB4 GT in Gunmetal Grey represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  58, 'Aston Martin DB6', 1967, 408814, '84,556', 'Petrol', 'Convertible', 'Automatic', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-84bbe3c3fd98?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN688824', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1967 Aston Martin DB6 in Rosso Corsa represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  59, 'Aston Martin DB5', 1963, 1127655, '77,393', 'Petrol', 'Roadster', 'Manual', 'Silver', 
  'https://images.unsplash.com/photo-LpbyDENbQQg?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN559258', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1963 Aston Martin DB5 in Silver represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  60, 'Aston Martin DB4 GT', 1963, 1860611, '61,535', 'Petrol', 'Targa', 'Automatic', 'Midnight Blue', 
  'https://images.unsplash.com/photo-hE49D3lQZ5w?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN518498', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1963 Aston Martin DB4 GT in Midnight Blue represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  61, 'Aston Martin DB5', 1964, 1066775, '30,212', 'Petrol', 'Targa', '4-Speed Manual', 'Gunmetal Grey', 
  'https://images.unsplash.com/photo-e_D3Z3K0i5g?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN864364', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1964 Aston Martin DB5 in Gunmetal Grey represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  62, 'Aston Martin DB6', 1965, 503210, '76,987', 'Petrol', 'Sedan', 'Automatic', 'British Racing Green', 
  'https://images.unsplash.com/photo-aq5X00a5G6A?auto=format&fit=crop&w=800&q=80', 'Concours Winner',
  'VIN884831', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1965 Aston Martin DB6 with only 76,987 miles, presented in immaculate British Racing Green.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  63, 'Aston Martin DB4 GT', 1958, 2311335, '80,869', 'Petrol', 'Sedan', 'Manual', 'Cream White', 
  'https://images.unsplash.com/photo-vpOeCk5amPU?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN295088', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1958 Aston Martin DB4 GT in Cream White represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  64, 'Aston Martin DB4 GT', 1961, 1767070, '79,728', 'Petrol', 'Roadster', '4-Speed Manual', 'British Racing Green', 
  'https://images.unsplash.com/photo-84bbe3c3fd98?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN877769', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1961 Aston Martin DB4 GT. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  65, 'Aston Martin DB4 GT', 1959, 2079619, '31,261', 'Petrol', 'Sedan', '4-Speed Manual', 'Gunmetal Grey', 
  'https://images.unsplash.com/photo-LpbyDENbQQg?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN203462', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1959 Aston Martin DB4 GT. Finished in stunning Gunmetal Grey, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  66, 'Aston Martin DB6', 1966, 358004, '41,135', 'Petrol', 'Sedan', 'Manual', 'Black', 
  'https://images.unsplash.com/photo-hE49D3lQZ5w?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN809874', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1966 Aston Martin DB6 with only 41,135 miles, presented in immaculate Black.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  67, 'Ferrari 275 GTB', 1965, 3025213, '63,813', 'Petrol', 'Sedan', 'Manual', 'Midnight Blue', 
  'https://images.unsplash.com/photo-Hw6_7y04V5I?auto=format&fit=crop&w=800&q=80', 'Rare Find',
  'VIN942508', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1965 Ferrari 275 GTB with only 63,813 miles, presented in immaculate Midnight Blue.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  68, 'Ferrari 275 GTB', 1965, 3909552, '64,733', 'Petrol', 'Convertible', '5-Speed Manual', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-e_D3Z3K0i5g?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN737214', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1965 Ferrari 275 GTB. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  69, 'Ferrari Dino 246 GT', 1974, 361216, '90,160', 'Petrol', 'Targa', 'Manual', 'Silver', 
  'https://images.unsplash.com/photo-aq5X00a5G6A?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN302459', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1974 Ferrari Dino 246 GT in Silver represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  70, 'Ferrari Dino 246 GT', 1973, 521971, '38,560', 'Petrol', 'Targa', 'Automatic', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-OS2w2lMvA7g?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN893513', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1973 Ferrari Dino 246 GT. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  71, 'Ferrari 275 GTB', 1966, 2612124, '92,115', 'Petrol', 'Sedan', 'Manual', 'Silver', 
  'https://images.unsplash.com/photo-_tV8s1G3yXg?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN142343', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1966 Ferrari 275 GTB. Finished in stunning Silver, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  72, 'Ferrari Dino 246 GT', 1974, 503015, '79,981', 'Petrol', 'Sedan', 'Manual', 'Midnight Blue', 
  'https://images.unsplash.com/photo-X16zXcbxU4U?auto=format&fit=crop&w=800&q=80', 'Rare Find',
  'VIN693287', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1974 Ferrari Dino 246 GT in Midnight Blue represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  73, 'Ferrari Dino 246 GT', 1973, 538118, '70,028', 'Petrol', 'Coupe', 'Automatic', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-Hw6_7y04V5I?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN652089', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1973 Ferrari Dino 246 GT. Finished in stunning Rosso Corsa, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  74, 'Ferrari 250 GTO', 1964, 41924557, '25,874', 'Petrol', 'Roadster', 'Automatic', 'British Racing Green', 
  'https://images.unsplash.com/photo-e_D3Z3K0i5g?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN591707', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1964 Ferrari 250 GTO. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  75, 'Ferrari 275 GTB', 1965, 3025694, '72,389', 'Petrol', 'Coupe', 'Automatic', 'Gunmetal Grey', 
  'https://images.unsplash.com/photo-aq5X00a5G6A?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN100004', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1965 Ferrari 275 GTB with only 72,389 miles, presented in immaculate Gunmetal Grey.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  76, 'Ferrari 250 GTO', 1964, 38261752, '68,795', 'Petrol', 'Targa', '4-Speed Manual', 'Black', 
  'https://images.unsplash.com/photo-OS2w2lMvA7g?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN163708', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1964 Ferrari 250 GTO. Finished in stunning Black, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  77, 'Ferrari Dino 246 GT', 1970, 488427, '32,697', 'Petrol', 'Sedan', 'Manual', 'Black', 
  'https://images.unsplash.com/photo-_tV8s1G3yXg?auto=format&fit=crop&w=800&q=80', 'Rare Find',
  'VIN629258', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1970 Ferrari Dino 246 GT. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  78, 'Ferrari 275 GTB', 1967, 3754638, '71,497', 'Petrol', 'Coupe', '4-Speed Manual', 'Gunmetal Grey', 
  'https://images.unsplash.com/photo-X16zXcbxU4U?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN478629', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1967 Ferrari 275 GTB with only 71,497 miles, presented in immaculate Gunmetal Grey.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  79, 'Ferrari 250 GTO', 1962, 20609742, '66,468', 'Petrol', 'Coupe', '5-Speed Manual', 'ChampagneGold', 
  'https://images.unsplash.com/photo-Hw6_7y04V5I?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN448538', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1962 Ferrari 250 GTO. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  80, 'Ferrari Dino 246 GT', 1974, 460141, '52,678', 'Petrol', 'Roadster', '5-Speed Manual', 'Black', 
  'https://images.unsplash.com/photo-e_D3Z3K0i5g?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN792554', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1974 Ferrari Dino 246 GT. Finished in stunning Black, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  81, 'Ferrari Dino 246 GT', 1970, 367149, '94,455', 'Petrol', 'Sedan', '5-Speed Manual', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-aq5X00a5G6A?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN730948', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1970 Ferrari Dino 246 GT. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  82, 'Porsche 356 Speedster', 1954, 252194, '23,638', 'Petrol', 'Targa', 'Automatic', 'British Racing Green', 
  'https://images.unsplash.com/photo-Dwu85P9SOIk?auto=format&fit=crop&w=800&q=80', 'Low Mileage',
  'VIN319937', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1954 Porsche 356 Speedster in British Racing Green represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  83, 'Porsche 356 Speedster', 1956, 286589, '19,610', 'Petrol', 'Coupe', '4-Speed Manual', 'Silver', 
  'https://images.unsplash.com/photo-_tV8s1G3yXg?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN146582', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1956 Porsche 356 Speedster with only 19,610 miles, presented in immaculate Silver.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  84, 'Porsche 550 Spyder', 1955, 4154367, '63,854', 'Petrol', 'Sedan', 'Manual', 'ChampagneGold', 
  'https://images.unsplash.com/photo-vpOeCk5amPU?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN392341', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1955 Porsche 550 Spyder with only 63,854 miles, presented in immaculate ChampagneGold.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  85, 'Porsche 911 Turbo (Classic)', 1988, 223663, '1,876', 'Petrol', 'Convertible', 'Automatic', 'British Racing Green', 
  'https://images.unsplash.com/photo-jR4Zf-riEjI?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN797237', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1988 Porsche 911 Turbo (Classic). A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  86, 'Porsche 356 Speedster', 1958, 322533, '54,353', 'Petrol', 'Convertible', 'Automatic', 'Silver', 
  'https://images.unsplash.com/photo-X16zXcbxU4U?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN943852', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1958 Porsche 356 Speedster. Finished in stunning Silver, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  87, 'Porsche 356 Speedster', 1955, 251251, '36,561', 'Petrol', 'Sedan', '5-Speed Manual', 'Black', 
  'https://images.unsplash.com/photo-N9Pf2J656aQ?auto=format&fit=crop&w=800&q=80', 'Rare Find',
  'VIN628118', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1955 Porsche 356 Speedster. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  88, 'Porsche 911 Turbo (Classic)', 1977, 231339, '10,829', 'Petrol', 'Targa', 'Automatic', 'Black', 
  'https://images.unsplash.com/photo-Dwu85P9SOIk?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN393414', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1977 Porsche 911 Turbo (Classic) in Black represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  89, 'Porsche 550 Spyder', 1953, 4098840, '32,312', 'Petrol', 'Targa', 'Manual', 'Rosso Corsa', 
  'https://images.unsplash.com/photo-_tV8s1G3yXg?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN114455', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1953 Porsche 550 Spyder with only 32,312 miles, presented in immaculate Rosso Corsa.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  90, 'Porsche 911 Turbo (Classic)', 1982, 130118, '69,939', 'Petrol', 'Sedan', '4-Speed Manual', 'Gunmetal Grey', 
  'https://images.unsplash.com/photo-vpOeCk5amPU?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN735189', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1982 Porsche 911 Turbo (Classic). Finished in stunning Gunmetal Grey, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  91, 'Porsche 911 Turbo (Classic)', 1979, 190733, '50,672', 'Petrol', 'Coupe', 'Automatic', 'Black', 
  'https://images.unsplash.com/photo-jR4Zf-riEjI?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN752779', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1979 Porsche 911 Turbo (Classic). Finished in stunning Black, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  92, 'Porsche 911 Turbo (Classic)', 1976, 224811, '1,544', 'Petrol', 'Roadster', '4-Speed Manual', 'Cream White', 
  'https://images.unsplash.com/photo-X16zXcbxU4U?auto=format&fit=crop&w=800&q=80', 'Low Mileage',
  'VIN590138', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'A true collector''s item: 1976 Porsche 911 Turbo (Classic) with only 1,544 miles, presented in immaculate Cream White.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  93, 'Porsche 356 Speedster', 1958, 317715, '27,883', 'Petrol', 'Sedan', 'Automatic', 'Black', 
  'https://images.unsplash.com/photo-N9Pf2J656aQ?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN134659', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1958 Porsche 356 Speedster in Black represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  94, 'Porsche 911 Turbo (Classic)', 1978, 159256, '11,799', 'Petrol', 'Coupe', 'Manual', 'Midnight Blue', 
  'https://images.unsplash.com/photo-Dwu85P9SOIk?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN949087', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'This rare 1978 Porsche 911 Turbo (Classic) in Midnight Blue represents the pinnacle of automotive engineering of its era.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  95, 'Porsche 356 Speedster', 1958, 302333, '61,606', 'Petrol', 'Convertible', '4-Speed Manual', 'Black', 
  'https://images.unsplash.com/photo-_tV8s1G3yXg?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN689807', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'Meticulously maintained 1958 Porsche 356 Speedster. A stunning addition to any serious collection.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

insert into public.vehicles (
  id, name, year, price, mileage, fuel, body_type, transmission, color, image, badge,
  vin, engine, horsepower, torque, drivetrain, description, features, specs
) values (
  96, 'Porsche 550 Spyder', 1953, 4410603, '38,818', 'Petrol', 'Roadster', 'Manual', 'Gunmetal Grey', 
  'https://images.unsplash.com/photo-vpOeCk5amPU?auto=format&fit=crop&w=800&q=80', NULL,
  'VIN704182', 'V8/V12', '300hp', '300lb-ft', 'RWD',
  'An exceptional example of the 1953 Porsche 550 Spyder. Finished in stunning Gunmetal Grey, this vehicle has been meticulously preserved.',
  '["Leather Seats","Original Radio","Service Records","Tool Kit","Spare Wheel"]',
  '{"engine":[{"name":"Engine","value":"Original Specs"}],"performance":[{"name":"0-60","value":"N/A"}]}'
);

select setval('vehicles_id_seq', (select max(id) from vehicles));
